#include "ROOT/RDataFrame.hxx"
#include "ROOT/RDFHelpers.hxx"
#include "RooTrace.h"
#include "TStopwatch.h"
#include <ROOT/RLogger.hxx>
#include "include/utility/Logger.hxx"
#include <TFile.h>
#include <TMap.h>
#include <filesystem>
#include <TObjString.h>
#include <TTree.h>
#include <TVector.h>
#include "onnxruntime_cxx_api.h"
#include <regex>
#include <string>
#include "include/utility/OnnxSessionManager.hxx"
#include "include/utility/CorrectionManager.hxx"
#include "include/genparticles.hxx"
#include "include/htxs.hxx"
#include "include/jets.hxx"
#include "include/lorentzvectors.hxx"
#include "include/met.hxx"
#include "include/ml.hxx"
#include "include/metfilter.hxx"
#include "include/pairselection.hxx"
#include "include/tripleselection.hxx"
#include "include/physicsobjects.hxx"
#include "include/quantities.hxx"
#include "include/reweighting.hxx"
#include "include/scalefactors.hxx"
#include "include/topreco.hxx"
#include "include/triggers.hxx"
#include "include/fakefactors.hxx"
ROOT::RDF::RNode Tau_1_VsEleTauID_SF_tt (ROOT::RDF::RNode df0, OnnxSessionManager &onnxSessionManager, CorrectionManager &correctionManager) {

        auto df1 = scalefactor::tau::id_vsEle(df0, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "VVLoose", "nom", "nom", "id_wgt_tau_vsEle_VVLoose_1", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df2 = scalefactor::tau::id_vsEle(df1, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "VLoose", "nom", "nom", "id_wgt_tau_vsEle_VLoose_1", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df3 = scalefactor::tau::id_vsEle(df2, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "Loose", "nom", "nom", "id_wgt_tau_vsEle_Loose_1", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df4 = scalefactor::tau::id_vsEle(df3, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "Medium", "nom", "nom", "id_wgt_tau_vsEle_Medium_1", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df5 = scalefactor::tau::id_vsEle(df4, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "Tight", "nom", "nom", "id_wgt_tau_vsEle_Tight_1", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df6 = scalefactor::tau::id_vsEle(df5, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "VTight", "nom", "nom", "id_wgt_tau_vsEle_VTight_1", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df7 = scalefactor::tau::id_vsEle(df6, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "VVTight", "nom", "nom", "id_wgt_tau_vsEle_VVTight_1", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df8 = scalefactor::tau::id_vsEle(df7, correctionManager, "eta_1__tauEs3prong1pizeroDown", "tau_decaymode_1__tauEs3prong1pizeroDown", "tau_gen_match_1__tauEs3prong1pizeroDown", {0,1,10,11}, "VVLoose", "nom", "nom", "id_wgt_tau_vsEle_VVLoose_1__tauEs3prong1pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df9 = scalefactor::tau::id_vsEle(df8, correctionManager, "eta_1__tauEs3prong1pizeroDown", "tau_decaymode_1__tauEs3prong1pizeroDown", "tau_gen_match_1__tauEs3prong1pizeroDown", {0,1,10,11}, "VLoose", "nom", "nom", "id_wgt_tau_vsEle_VLoose_1__tauEs3prong1pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df10 = scalefactor::tau::id_vsEle(df9, correctionManager, "eta_1__tauEs3prong1pizeroDown", "tau_decaymode_1__tauEs3prong1pizeroDown", "tau_gen_match_1__tauEs3prong1pizeroDown", {0,1,10,11}, "Loose", "nom", "nom", "id_wgt_tau_vsEle_Loose_1__tauEs3prong1pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df11 = scalefactor::tau::id_vsEle(df10, correctionManager, "eta_1__tauEs3prong1pizeroDown", "tau_decaymode_1__tauEs3prong1pizeroDown", "tau_gen_match_1__tauEs3prong1pizeroDown", {0,1,10,11}, "Medium", "nom", "nom", "id_wgt_tau_vsEle_Medium_1__tauEs3prong1pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df12 = scalefactor::tau::id_vsEle(df11, correctionManager, "eta_1__tauEs3prong1pizeroDown", "tau_decaymode_1__tauEs3prong1pizeroDown", "tau_gen_match_1__tauEs3prong1pizeroDown", {0,1,10,11}, "Tight", "nom", "nom", "id_wgt_tau_vsEle_Tight_1__tauEs3prong1pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df13 = scalefactor::tau::id_vsEle(df12, correctionManager, "eta_1__tauEs3prong1pizeroDown", "tau_decaymode_1__tauEs3prong1pizeroDown", "tau_gen_match_1__tauEs3prong1pizeroDown", {0,1,10,11}, "VTight", "nom", "nom", "id_wgt_tau_vsEle_VTight_1__tauEs3prong1pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df14 = scalefactor::tau::id_vsEle(df13, correctionManager, "eta_1__tauEs3prong1pizeroDown", "tau_decaymode_1__tauEs3prong1pizeroDown", "tau_gen_match_1__tauEs3prong1pizeroDown", {0,1,10,11}, "VVTight", "nom", "nom", "id_wgt_tau_vsEle_VVTight_1__tauEs3prong1pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df15 = scalefactor::tau::id_vsEle(df14, correctionManager, "eta_1__tauEs1prong0pizeroDown", "tau_decaymode_1__tauEs1prong0pizeroDown", "tau_gen_match_1__tauEs1prong0pizeroDown", {0,1,10,11}, "VVLoose", "nom", "nom", "id_wgt_tau_vsEle_VVLoose_1__tauEs1prong0pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df16 = scalefactor::tau::id_vsEle(df15, correctionManager, "eta_1__tauEs1prong0pizeroDown", "tau_decaymode_1__tauEs1prong0pizeroDown", "tau_gen_match_1__tauEs1prong0pizeroDown", {0,1,10,11}, "VLoose", "nom", "nom", "id_wgt_tau_vsEle_VLoose_1__tauEs1prong0pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df17 = scalefactor::tau::id_vsEle(df16, correctionManager, "eta_1__tauEs1prong0pizeroDown", "tau_decaymode_1__tauEs1prong0pizeroDown", "tau_gen_match_1__tauEs1prong0pizeroDown", {0,1,10,11}, "Loose", "nom", "nom", "id_wgt_tau_vsEle_Loose_1__tauEs1prong0pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df18 = scalefactor::tau::id_vsEle(df17, correctionManager, "eta_1__tauEs1prong0pizeroDown", "tau_decaymode_1__tauEs1prong0pizeroDown", "tau_gen_match_1__tauEs1prong0pizeroDown", {0,1,10,11}, "Medium", "nom", "nom", "id_wgt_tau_vsEle_Medium_1__tauEs1prong0pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df19 = scalefactor::tau::id_vsEle(df18, correctionManager, "eta_1__tauEs1prong0pizeroDown", "tau_decaymode_1__tauEs1prong0pizeroDown", "tau_gen_match_1__tauEs1prong0pizeroDown", {0,1,10,11}, "Tight", "nom", "nom", "id_wgt_tau_vsEle_Tight_1__tauEs1prong0pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df20 = scalefactor::tau::id_vsEle(df19, correctionManager, "eta_1__tauEs1prong0pizeroDown", "tau_decaymode_1__tauEs1prong0pizeroDown", "tau_gen_match_1__tauEs1prong0pizeroDown", {0,1,10,11}, "VTight", "nom", "nom", "id_wgt_tau_vsEle_VTight_1__tauEs1prong0pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df21 = scalefactor::tau::id_vsEle(df20, correctionManager, "eta_1__tauEs1prong0pizeroDown", "tau_decaymode_1__tauEs1prong0pizeroDown", "tau_gen_match_1__tauEs1prong0pizeroDown", {0,1,10,11}, "VVTight", "nom", "nom", "id_wgt_tau_vsEle_VVTight_1__tauEs1prong0pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df22 = scalefactor::tau::id_vsEle(df21, correctionManager, "eta_1__tauEs3prong1pizeroUp", "tau_decaymode_1__tauEs3prong1pizeroUp", "tau_gen_match_1__tauEs3prong1pizeroUp", {0,1,10,11}, "VVLoose", "nom", "nom", "id_wgt_tau_vsEle_VVLoose_1__tauEs3prong1pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df23 = scalefactor::tau::id_vsEle(df22, correctionManager, "eta_1__tauEs3prong1pizeroUp", "tau_decaymode_1__tauEs3prong1pizeroUp", "tau_gen_match_1__tauEs3prong1pizeroUp", {0,1,10,11}, "VLoose", "nom", "nom", "id_wgt_tau_vsEle_VLoose_1__tauEs3prong1pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df24 = scalefactor::tau::id_vsEle(df23, correctionManager, "eta_1__tauEs3prong1pizeroUp", "tau_decaymode_1__tauEs3prong1pizeroUp", "tau_gen_match_1__tauEs3prong1pizeroUp", {0,1,10,11}, "Loose", "nom", "nom", "id_wgt_tau_vsEle_Loose_1__tauEs3prong1pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df25 = scalefactor::tau::id_vsEle(df24, correctionManager, "eta_1__tauEs3prong1pizeroUp", "tau_decaymode_1__tauEs3prong1pizeroUp", "tau_gen_match_1__tauEs3prong1pizeroUp", {0,1,10,11}, "Medium", "nom", "nom", "id_wgt_tau_vsEle_Medium_1__tauEs3prong1pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df26 = scalefactor::tau::id_vsEle(df25, correctionManager, "eta_1__tauEs3prong1pizeroUp", "tau_decaymode_1__tauEs3prong1pizeroUp", "tau_gen_match_1__tauEs3prong1pizeroUp", {0,1,10,11}, "Tight", "nom", "nom", "id_wgt_tau_vsEle_Tight_1__tauEs3prong1pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df27 = scalefactor::tau::id_vsEle(df26, correctionManager, "eta_1__tauEs3prong1pizeroUp", "tau_decaymode_1__tauEs3prong1pizeroUp", "tau_gen_match_1__tauEs3prong1pizeroUp", {0,1,10,11}, "VTight", "nom", "nom", "id_wgt_tau_vsEle_VTight_1__tauEs3prong1pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df28 = scalefactor::tau::id_vsEle(df27, correctionManager, "eta_1__tauEs3prong1pizeroUp", "tau_decaymode_1__tauEs3prong1pizeroUp", "tau_gen_match_1__tauEs3prong1pizeroUp", {0,1,10,11}, "VVTight", "nom", "nom", "id_wgt_tau_vsEle_VVTight_1__tauEs3prong1pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df29 = scalefactor::tau::id_vsEle(df28, correctionManager, "eta_1__tauEs1prong1pizeroDown", "tau_decaymode_1__tauEs1prong1pizeroDown", "tau_gen_match_1__tauEs1prong1pizeroDown", {0,1,10,11}, "VVLoose", "nom", "nom", "id_wgt_tau_vsEle_VVLoose_1__tauEs1prong1pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df30 = scalefactor::tau::id_vsEle(df29, correctionManager, "eta_1__tauEs1prong1pizeroDown", "tau_decaymode_1__tauEs1prong1pizeroDown", "tau_gen_match_1__tauEs1prong1pizeroDown", {0,1,10,11}, "VLoose", "nom", "nom", "id_wgt_tau_vsEle_VLoose_1__tauEs1prong1pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df31 = scalefactor::tau::id_vsEle(df30, correctionManager, "eta_1__tauEs1prong1pizeroDown", "tau_decaymode_1__tauEs1prong1pizeroDown", "tau_gen_match_1__tauEs1prong1pizeroDown", {0,1,10,11}, "Loose", "nom", "nom", "id_wgt_tau_vsEle_Loose_1__tauEs1prong1pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df32 = scalefactor::tau::id_vsEle(df31, correctionManager, "eta_1__tauEs1prong1pizeroDown", "tau_decaymode_1__tauEs1prong1pizeroDown", "tau_gen_match_1__tauEs1prong1pizeroDown", {0,1,10,11}, "Medium", "nom", "nom", "id_wgt_tau_vsEle_Medium_1__tauEs1prong1pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df33 = scalefactor::tau::id_vsEle(df32, correctionManager, "eta_1__tauEs1prong1pizeroDown", "tau_decaymode_1__tauEs1prong1pizeroDown", "tau_gen_match_1__tauEs1prong1pizeroDown", {0,1,10,11}, "Tight", "nom", "nom", "id_wgt_tau_vsEle_Tight_1__tauEs1prong1pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df34 = scalefactor::tau::id_vsEle(df33, correctionManager, "eta_1__tauEs1prong1pizeroDown", "tau_decaymode_1__tauEs1prong1pizeroDown", "tau_gen_match_1__tauEs1prong1pizeroDown", {0,1,10,11}, "VTight", "nom", "nom", "id_wgt_tau_vsEle_VTight_1__tauEs1prong1pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df35 = scalefactor::tau::id_vsEle(df34, correctionManager, "eta_1__tauEs1prong1pizeroDown", "tau_decaymode_1__tauEs1prong1pizeroDown", "tau_gen_match_1__tauEs1prong1pizeroDown", {0,1,10,11}, "VVTight", "nom", "nom", "id_wgt_tau_vsEle_VVTight_1__tauEs1prong1pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df36 = scalefactor::tau::id_vsEle(df35, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "VVLoose", "nom", "up", "id_wgt_tau_vsEle_VVLoose_1__vsEleEndcapUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df37 = scalefactor::tau::id_vsEle(df36, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "VLoose", "nom", "up", "id_wgt_tau_vsEle_VLoose_1__vsEleEndcapUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df38 = scalefactor::tau::id_vsEle(df37, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "Loose", "nom", "up", "id_wgt_tau_vsEle_Loose_1__vsEleEndcapUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df39 = scalefactor::tau::id_vsEle(df38, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "Medium", "nom", "up", "id_wgt_tau_vsEle_Medium_1__vsEleEndcapUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df40 = scalefactor::tau::id_vsEle(df39, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "Tight", "nom", "up", "id_wgt_tau_vsEle_Tight_1__vsEleEndcapUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df41 = scalefactor::tau::id_vsEle(df40, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "VTight", "nom", "up", "id_wgt_tau_vsEle_VTight_1__vsEleEndcapUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df42 = scalefactor::tau::id_vsEle(df41, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "VVTight", "nom", "up", "id_wgt_tau_vsEle_VVTight_1__vsEleEndcapUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df43 = scalefactor::tau::id_vsEle(df42, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "VVLoose", "up", "nom", "id_wgt_tau_vsEle_VVLoose_1__vsEleBarrelUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df44 = scalefactor::tau::id_vsEle(df43, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "VLoose", "up", "nom", "id_wgt_tau_vsEle_VLoose_1__vsEleBarrelUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df45 = scalefactor::tau::id_vsEle(df44, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "Loose", "up", "nom", "id_wgt_tau_vsEle_Loose_1__vsEleBarrelUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df46 = scalefactor::tau::id_vsEle(df45, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "Medium", "up", "nom", "id_wgt_tau_vsEle_Medium_1__vsEleBarrelUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df47 = scalefactor::tau::id_vsEle(df46, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "Tight", "up", "nom", "id_wgt_tau_vsEle_Tight_1__vsEleBarrelUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df48 = scalefactor::tau::id_vsEle(df47, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "VTight", "up", "nom", "id_wgt_tau_vsEle_VTight_1__vsEleBarrelUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df49 = scalefactor::tau::id_vsEle(df48, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "VVTight", "up", "nom", "id_wgt_tau_vsEle_VVTight_1__vsEleBarrelUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df50 = scalefactor::tau::id_vsEle(df49, correctionManager, "eta_1__tauEs1prong1pizeroUp", "tau_decaymode_1__tauEs1prong1pizeroUp", "tau_gen_match_1__tauEs1prong1pizeroUp", {0,1,10,11}, "VVLoose", "nom", "nom", "id_wgt_tau_vsEle_VVLoose_1__tauEs1prong1pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df51 = scalefactor::tau::id_vsEle(df50, correctionManager, "eta_1__tauEs1prong1pizeroUp", "tau_decaymode_1__tauEs1prong1pizeroUp", "tau_gen_match_1__tauEs1prong1pizeroUp", {0,1,10,11}, "VLoose", "nom", "nom", "id_wgt_tau_vsEle_VLoose_1__tauEs1prong1pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df52 = scalefactor::tau::id_vsEle(df51, correctionManager, "eta_1__tauEs1prong1pizeroUp", "tau_decaymode_1__tauEs1prong1pizeroUp", "tau_gen_match_1__tauEs1prong1pizeroUp", {0,1,10,11}, "Loose", "nom", "nom", "id_wgt_tau_vsEle_Loose_1__tauEs1prong1pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df53 = scalefactor::tau::id_vsEle(df52, correctionManager, "eta_1__tauEs1prong1pizeroUp", "tau_decaymode_1__tauEs1prong1pizeroUp", "tau_gen_match_1__tauEs1prong1pizeroUp", {0,1,10,11}, "Medium", "nom", "nom", "id_wgt_tau_vsEle_Medium_1__tauEs1prong1pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df54 = scalefactor::tau::id_vsEle(df53, correctionManager, "eta_1__tauEs1prong1pizeroUp", "tau_decaymode_1__tauEs1prong1pizeroUp", "tau_gen_match_1__tauEs1prong1pizeroUp", {0,1,10,11}, "Tight", "nom", "nom", "id_wgt_tau_vsEle_Tight_1__tauEs1prong1pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df55 = scalefactor::tau::id_vsEle(df54, correctionManager, "eta_1__tauEs1prong1pizeroUp", "tau_decaymode_1__tauEs1prong1pizeroUp", "tau_gen_match_1__tauEs1prong1pizeroUp", {0,1,10,11}, "VTight", "nom", "nom", "id_wgt_tau_vsEle_VTight_1__tauEs1prong1pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df56 = scalefactor::tau::id_vsEle(df55, correctionManager, "eta_1__tauEs1prong1pizeroUp", "tau_decaymode_1__tauEs1prong1pizeroUp", "tau_gen_match_1__tauEs1prong1pizeroUp", {0,1,10,11}, "VVTight", "nom", "nom", "id_wgt_tau_vsEle_VVTight_1__tauEs1prong1pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df57 = scalefactor::tau::id_vsEle(df56, correctionManager, "eta_1__tauEs1prong0pizeroUp", "tau_decaymode_1__tauEs1prong0pizeroUp", "tau_gen_match_1__tauEs1prong0pizeroUp", {0,1,10,11}, "VVLoose", "nom", "nom", "id_wgt_tau_vsEle_VVLoose_1__tauEs1prong0pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df58 = scalefactor::tau::id_vsEle(df57, correctionManager, "eta_1__tauEs1prong0pizeroUp", "tau_decaymode_1__tauEs1prong0pizeroUp", "tau_gen_match_1__tauEs1prong0pizeroUp", {0,1,10,11}, "VLoose", "nom", "nom", "id_wgt_tau_vsEle_VLoose_1__tauEs1prong0pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df59 = scalefactor::tau::id_vsEle(df58, correctionManager, "eta_1__tauEs1prong0pizeroUp", "tau_decaymode_1__tauEs1prong0pizeroUp", "tau_gen_match_1__tauEs1prong0pizeroUp", {0,1,10,11}, "Loose", "nom", "nom", "id_wgt_tau_vsEle_Loose_1__tauEs1prong0pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df60 = scalefactor::tau::id_vsEle(df59, correctionManager, "eta_1__tauEs1prong0pizeroUp", "tau_decaymode_1__tauEs1prong0pizeroUp", "tau_gen_match_1__tauEs1prong0pizeroUp", {0,1,10,11}, "Medium", "nom", "nom", "id_wgt_tau_vsEle_Medium_1__tauEs1prong0pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df61 = scalefactor::tau::id_vsEle(df60, correctionManager, "eta_1__tauEs1prong0pizeroUp", "tau_decaymode_1__tauEs1prong0pizeroUp", "tau_gen_match_1__tauEs1prong0pizeroUp", {0,1,10,11}, "Tight", "nom", "nom", "id_wgt_tau_vsEle_Tight_1__tauEs1prong0pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df62 = scalefactor::tau::id_vsEle(df61, correctionManager, "eta_1__tauEs1prong0pizeroUp", "tau_decaymode_1__tauEs1prong0pizeroUp", "tau_gen_match_1__tauEs1prong0pizeroUp", {0,1,10,11}, "VTight", "nom", "nom", "id_wgt_tau_vsEle_VTight_1__tauEs1prong0pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df63 = scalefactor::tau::id_vsEle(df62, correctionManager, "eta_1__tauEs1prong0pizeroUp", "tau_decaymode_1__tauEs1prong0pizeroUp", "tau_gen_match_1__tauEs1prong0pizeroUp", {0,1,10,11}, "VVTight", "nom", "nom", "id_wgt_tau_vsEle_VVTight_1__tauEs1prong0pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df64 = scalefactor::tau::id_vsEle(df63, correctionManager, "eta_1__tauEs3prong0pizeroDown", "tau_decaymode_1__tauEs3prong0pizeroDown", "tau_gen_match_1__tauEs3prong0pizeroDown", {0,1,10,11}, "VVLoose", "nom", "nom", "id_wgt_tau_vsEle_VVLoose_1__tauEs3prong0pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df65 = scalefactor::tau::id_vsEle(df64, correctionManager, "eta_1__tauEs3prong0pizeroDown", "tau_decaymode_1__tauEs3prong0pizeroDown", "tau_gen_match_1__tauEs3prong0pizeroDown", {0,1,10,11}, "VLoose", "nom", "nom", "id_wgt_tau_vsEle_VLoose_1__tauEs3prong0pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df66 = scalefactor::tau::id_vsEle(df65, correctionManager, "eta_1__tauEs3prong0pizeroDown", "tau_decaymode_1__tauEs3prong0pizeroDown", "tau_gen_match_1__tauEs3prong0pizeroDown", {0,1,10,11}, "Loose", "nom", "nom", "id_wgt_tau_vsEle_Loose_1__tauEs3prong0pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df67 = scalefactor::tau::id_vsEle(df66, correctionManager, "eta_1__tauEs3prong0pizeroDown", "tau_decaymode_1__tauEs3prong0pizeroDown", "tau_gen_match_1__tauEs3prong0pizeroDown", {0,1,10,11}, "Medium", "nom", "nom", "id_wgt_tau_vsEle_Medium_1__tauEs3prong0pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df68 = scalefactor::tau::id_vsEle(df67, correctionManager, "eta_1__tauEs3prong0pizeroDown", "tau_decaymode_1__tauEs3prong0pizeroDown", "tau_gen_match_1__tauEs3prong0pizeroDown", {0,1,10,11}, "Tight", "nom", "nom", "id_wgt_tau_vsEle_Tight_1__tauEs3prong0pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df69 = scalefactor::tau::id_vsEle(df68, correctionManager, "eta_1__tauEs3prong0pizeroDown", "tau_decaymode_1__tauEs3prong0pizeroDown", "tau_gen_match_1__tauEs3prong0pizeroDown", {0,1,10,11}, "VTight", "nom", "nom", "id_wgt_tau_vsEle_VTight_1__tauEs3prong0pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df70 = scalefactor::tau::id_vsEle(df69, correctionManager, "eta_1__tauEs3prong0pizeroDown", "tau_decaymode_1__tauEs3prong0pizeroDown", "tau_gen_match_1__tauEs3prong0pizeroDown", {0,1,10,11}, "VVTight", "nom", "nom", "id_wgt_tau_vsEle_VVTight_1__tauEs3prong0pizeroDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df71 = scalefactor::tau::id_vsEle(df70, correctionManager, "eta_1__tauEs3prong0pizeroUp", "tau_decaymode_1__tauEs3prong0pizeroUp", "tau_gen_match_1__tauEs3prong0pizeroUp", {0,1,10,11}, "VVLoose", "nom", "nom", "id_wgt_tau_vsEle_VVLoose_1__tauEs3prong0pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df72 = scalefactor::tau::id_vsEle(df71, correctionManager, "eta_1__tauEs3prong0pizeroUp", "tau_decaymode_1__tauEs3prong0pizeroUp", "tau_gen_match_1__tauEs3prong0pizeroUp", {0,1,10,11}, "VLoose", "nom", "nom", "id_wgt_tau_vsEle_VLoose_1__tauEs3prong0pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df73 = scalefactor::tau::id_vsEle(df72, correctionManager, "eta_1__tauEs3prong0pizeroUp", "tau_decaymode_1__tauEs3prong0pizeroUp", "tau_gen_match_1__tauEs3prong0pizeroUp", {0,1,10,11}, "Loose", "nom", "nom", "id_wgt_tau_vsEle_Loose_1__tauEs3prong0pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df74 = scalefactor::tau::id_vsEle(df73, correctionManager, "eta_1__tauEs3prong0pizeroUp", "tau_decaymode_1__tauEs3prong0pizeroUp", "tau_gen_match_1__tauEs3prong0pizeroUp", {0,1,10,11}, "Medium", "nom", "nom", "id_wgt_tau_vsEle_Medium_1__tauEs3prong0pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df75 = scalefactor::tau::id_vsEle(df74, correctionManager, "eta_1__tauEs3prong0pizeroUp", "tau_decaymode_1__tauEs3prong0pizeroUp", "tau_gen_match_1__tauEs3prong0pizeroUp", {0,1,10,11}, "Tight", "nom", "nom", "id_wgt_tau_vsEle_Tight_1__tauEs3prong0pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df76 = scalefactor::tau::id_vsEle(df75, correctionManager, "eta_1__tauEs3prong0pizeroUp", "tau_decaymode_1__tauEs3prong0pizeroUp", "tau_gen_match_1__tauEs3prong0pizeroUp", {0,1,10,11}, "VTight", "nom", "nom", "id_wgt_tau_vsEle_VTight_1__tauEs3prong0pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df77 = scalefactor::tau::id_vsEle(df76, correctionManager, "eta_1__tauEs3prong0pizeroUp", "tau_decaymode_1__tauEs3prong0pizeroUp", "tau_gen_match_1__tauEs3prong0pizeroUp", {0,1,10,11}, "VVTight", "nom", "nom", "id_wgt_tau_vsEle_VVTight_1__tauEs3prong0pizeroUp", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df78 = scalefactor::tau::id_vsEle(df77, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "VVLoose", "down", "nom", "id_wgt_tau_vsEle_VVLoose_1__vsEleBarrelDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df79 = scalefactor::tau::id_vsEle(df78, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "VLoose", "down", "nom", "id_wgt_tau_vsEle_VLoose_1__vsEleBarrelDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df80 = scalefactor::tau::id_vsEle(df79, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "Loose", "down", "nom", "id_wgt_tau_vsEle_Loose_1__vsEleBarrelDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df81 = scalefactor::tau::id_vsEle(df80, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "Medium", "down", "nom", "id_wgt_tau_vsEle_Medium_1__vsEleBarrelDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df82 = scalefactor::tau::id_vsEle(df81, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "Tight", "down", "nom", "id_wgt_tau_vsEle_Tight_1__vsEleBarrelDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df83 = scalefactor::tau::id_vsEle(df82, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "VTight", "down", "nom", "id_wgt_tau_vsEle_VTight_1__vsEleBarrelDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df84 = scalefactor::tau::id_vsEle(df83, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "VVTight", "down", "nom", "id_wgt_tau_vsEle_VVTight_1__vsEleBarrelDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df85 = scalefactor::tau::id_vsEle(df84, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "VVLoose", "nom", "down", "id_wgt_tau_vsEle_VVLoose_1__vsEleEndcapDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df86 = scalefactor::tau::id_vsEle(df85, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "VLoose", "nom", "down", "id_wgt_tau_vsEle_VLoose_1__vsEleEndcapDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df87 = scalefactor::tau::id_vsEle(df86, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "Loose", "nom", "down", "id_wgt_tau_vsEle_Loose_1__vsEleEndcapDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df88 = scalefactor::tau::id_vsEle(df87, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "Medium", "nom", "down", "id_wgt_tau_vsEle_Medium_1__vsEleEndcapDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df89 = scalefactor::tau::id_vsEle(df88, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "Tight", "nom", "down", "id_wgt_tau_vsEle_Tight_1__vsEleEndcapDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df90 = scalefactor::tau::id_vsEle(df89, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "VTight", "nom", "down", "id_wgt_tau_vsEle_VTight_1__vsEleEndcapDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    auto df91 = scalefactor::tau::id_vsEle(df90, correctionManager, "eta_1", "tau_decaymode_1", "tau_gen_match_1", {0,1,10,11}, "VVTight", "nom", "down", "id_wgt_tau_vsEle_VVTight_1__vsEleEndcapDown", "data/jsonpog-integration/POG/TAU/2018_UL/tau.json.gz", "DeepTau2017v2p1VSe");
    return df91;

}
